kind: pipeline
name: default

steps:
- name: node
  image: guoxudongdocker/node-drone
  commands:
  - rm -rf ./dist/static/ && rm -rf ./dist/index.html
  - npm install
  - npm run build
  volumes:
  - name: npmcache
    path: /drone/src/node_modules


- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    repo: hub.dh.com/leansite/web
    registry: hub.dh.com
    tags: ${DRONE_BUILD_NUMBER}
    context: ./dist
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: daemon
    path: /etc/docker/certs.d/hub.dh.com


- name: run
  image: hub.dh.com/library/drone-ssh
  settings:
    host: 192.168.2.59
    username: root
    password:
      from_secret: ssh_password
    port: 22
    script:
    - bash /usr/local/bin/webtag.sh ${DRONE_BUILD_NUMBER}

- name: 钉钉通知
  image: hub.dh.com/library/dingtalk:1
  settings:
    tpl: "http://192.168.2.59"



volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: daemon
  host:
    path: /etc/docker/certs.d/hub.dh.com
- name: npmcache
  host:
    path: /var/lib/npm
trigger:
  branch:
  - master
  event:
  - push

